### ISSUE TITLE
How to get block height?

### ISSUE THREAD

**Issue by ChzenChzen** [near/workspaces-rs#127]
Is it possible to get block height for an executed call? I see only block hash.

**Comment by ChaoticTempest** [comment]
This info is not directly available from the call. You'd have to do a separate call into getting a specific block via the block hash, but it seems `worker.view_block` isn't available. I'll add that now

**Comment by ChzenChzen** [comment]
yeah, I've solved it:
```rust
async fn get_block_height(block_hash: CryptoHash) -> Result<u64> {
    let testnet_client = JsonRpcClient::connect(NEAR_TESTNET_ARCHIVAL_RPC_URL);
    let request = methods::block::RpcBlockRequest {
        block_reference: BlockReference::BlockId(BlockId::Hash(block_hash)),
    };
    let result = testnet_client.call(request).await?;
    Ok(result.header.height)
}
```
but it's better to have such option inside `workspaces-rs`
