### ISSUE TITLE
Unintuitive API for call results

### ISSUE THREAD

**Issue by willemneal** [near/workspaces-rs#131]
As noted by this diff:

[https://github.com/AhaLabs/bootme/pull/1/commits/6e970407d44a42b04005430c806107fa6c4cc207](https://github.com/AhaLabs/bootme/pull/1/commits/6e970407d44a42b04005430c806107fa6c4cc207)

I had expected to execute the call and then check if its call result failed. Whereas instead `transact` returned an Error.

Does this mean that `res.is_failure()` can never be true because the call result won't arrive due to the error being returned? Shouldn't user's contract errors be treated as normal expected behavior?

Something that would make this more clear is `transact_raw` in order to get back the raw result from RPC, which already seems to be the case if the transaction succeeds.

**Comment by ChaoticTempest** [comment]
> I had expected to execute the call and then check if its call result failed. Whereas instead transact returned an Error.
> 
>Does this mean that res.is_failure() can never be true because the call result won't arrive due to the error being returned? Shouldn't user's contract errors be treated as normal expected behavior?

This is true, I'm going through the UX of how results are handled from calling into a transaction, and how its being done right now might be problematic for what you're mentioning. Originally, was going to add all the details into the error object included in the Result, but with https://github.com/near/workspaces-rs/issues/100, think its worth going back the other way and force users to call into a separate method to alert that the transaction succeeded.

So something like this should be preferable:
```
#[must_use]
struct CalExecutionDetails { ... }
impl CalExecutionDetails  {
    fn success() -> anyhow::Result<...>;
}
```
Only downside is that this is a breaking change

> Something that would make this more clear is transact_raw in order to get back the raw result from RPC, which already seems to be the case if the transaction succeeds.

could be an alternative to the breaking API, but would add `transact_raw` to everywhere that also has `transact`
