### ISSUE TITLE
Is there a reason that CallExecutionDetails.try_into_bytes is private?

### ISSUE THREAD

**Issue by willemneal** [near/workspaces-rs#132]
I need to access the raw bytes, but seem to have to reimplement this to access them:

https://github.com/near/workspaces-rs/blob/50206b6ac65b8e6b225d848862f8dc25c8b4d2b2/workspaces/src/result.rs#L84-L92

**Comment by willemneal** [comment]
In fact I can't implement outside the crate this because the `status` field is also private.

**Comment by austinabell** [comment]
that's very valid. This function probably should be exposed (not sure under that function name, though)

**Comment by ChaoticTempest** [comment]
definitely an assumption that only Json or Borsh deserialization would be needed. Not sure what other name to give it though, maybe just `bytes()`?

**Comment by austinabell** [comment]
> definitely an assumption that only Json or Borsh deserialization would be needed. Not sure what other name to give it though, maybe just `bytes()`?

Another candidate: `raw_bytes` or `return_bytes`

**Comment by ChaoticTempest** [comment]
Went with `raw_bytes` in https://github.com/near/workspaces-rs/pull/133
