### ISSUE TITLE
Support for JSVM contracts

### ISSUE THREAD

**Issue by ChaoticTempest** [near/workspaces-rs#141]
With `workspaces-js` having direct support for the JS enclave, it would also be great to add it here into the RS edition as well if someone wanted to go this route. It should be under the `unstable` feature flag as the JSVM is also likely to change

**Comment by ChaoticTempest** [comment]
@volovyk-s @ailisp, adding this issue if we want to go in this direction before the June release

**Comment by ailisp** [comment]
Good idea! IMO workspaces-rs support can be after near-sdk-js 1.0 release.

**Comment by volovyk-s** [comment]
Not sure what you mean by "workspaces-js having direct support for the JS enclave". Workspaces JS does not have any Enclave integration for now. Only `near-sdk-js/examples`, where we show, how to deploy JSVM contract, etc.

**Comment by ChaoticTempest** [comment]
ahh yeah I meant that there was an example of how someone can deploy the JS enclave, but this issue can definitely expand to add more JSVM specific APIs
