### ISSUE TITLE
Function `json` of `ViewResultDetails` fails on parsing `Option::None`

### ISSUE THREAD

**Issue by riversyang** [near/workspaces-rs#145]
When using the function `json` of `ViewResultDetails` to parse the return value of a view function with return type `Option<T>`, if the view function returns `Option::None`, the function `json` will produce an error like `error while parsing method call result: [data did not match any variant of untagged enum QueryResponseKind]` rather than return a normal `Option::<T>::None`.

As it is hard for the testing code to determine that this is a failed function call or the view function returns `Option::None`, I think current implementation is not correct, at least not good enough.

**Comment by riversyang** [comment]
I'm sorry, it's my mistake.

The case is, the function `view` of `CallTransaction` will produce the error like `error while parsing method call result: [data did not match any variant of untagged enum QueryResponseKind]` if you provide wrong parameters to the calling view function. The problem is not in the function `json`. I confused to the message at first.

As the error message is OK for the case, I think the issue can be closed.

**Comment by ChaoticTempest** [comment]
Thanks for bringing this to my attention! The error message `error while parsing method call result: [data did not match any variant of untagged enum QueryResponseKind`  is pretty unintuitive and currently is being worked on right now within the client libraries. @miraclx, do we have any updates on this one?

**Comment by miraclx** [comment]
Just saw this. Yeah, it was fixed quite a while ago. https://github.com/near/near-jsonrpc-client-rs/issues/74

Updating to workspaces v0.4.0 should have it resolved.
