### ISSUE TITLE
Gas price not available from block

### ISSUE THREAD

**Issue by austinabell** [near/workspaces-rs#146]
This functionality is important because if someone wanted to calculate the amount of gas burnt in NEAR, they need a way to calculate this.

[https://docs.rs/workspaces/0.3.0/workspaces/struct.Block.html](https://docs.rs/workspaces/0.3.0/workspaces/struct.Block.html) is current API

To expand on this, it would be very useful to have a convenience function on `ExecutionOutcome` that allows retrieving this, since [only the gas value is accessible](https://docs.rs/workspaces/latest/workspaces/result/struct.ExecutionOutcome.html#structfield.gas_burnt)

**Comment by bharath-123** [comment]
+1 It would be great if we could have the amount of gas burnt in NEAR for the tx rather than just the gas units! :D

**Comment by austinabell** [comment]
Closing because of #168 seems to close this. Unsure if exposing the block's gas price https://github.com/near/workspaces-rs/blob/main/workspaces/src/types/block.rs#L36-L41
