### ISSUE TITLE
ExecutionOutcome does not include tokens_burnt

### ISSUE THREAD

**Issue by trezbouchez** [near/workspaces-rs#151]
As a contract developer I would like to be able to write robust end-to-end tests that include verification of the signer account balance to confirm the attached storage deposits are correctly handled (kept or refunded). To be able to correctly reconcile the resulting account balance I first need to be able to determine how much tokens were burnt to cover gas costs. Then the remaining balance difference is deposit-related and can be used to check the correctness of deposit handling. Unfortunately, it seems that the Rust version of the Workspaces does not report tokens_burnt. The Workspaces Rust version of the ExecutionOutcome struct is out of sync with core version (as declared in [https://github.com/near/nearcore/blob/master/core/primitives/src/transaction.rs](https://github.com/near/nearcore/blob/master/core/primitives/src/transaction.rs)) where the latter includes some extra fields (tokens_burnt being one of them).

**Comment by ChaoticTempest** [comment]
Whoops, don't know how this field slipped when I was adding the others, but thanks for bringing this to my attention! This PR resolves it: https://github.com/near/workspaces-rs/pull/168

**Comment by trezbouchez** [comment]
Thanks, @ChaoticTempest!
