### ISSUE TITLE
NearCore supported M1 Native

### ISSUE THREAD

**Issue by paulo20223** [near/workspaces-rs#160]
near-sandbox:
https://github.com/near/nearcore/actions/runs/2554539788

https://s3-us-west-1.amazonaws.com/build.nearprotocol.com/nearcore/Darwin-arm64/VLAD-test/c90ac67bc16ba9acbd43104eeb1ba73b6600cca9/stable/near-sandbox.tar.gz

NearCore supported M1 and I can build it myself.
I set NEAR_SANDBOX_BIN_PATH and DOCS_RS.
But when i want build test i got error. compile_error!("Unsupported platform").

**Comment by paulo20223** [comment]
You can use 

workspaces = { git = "https://github.com/paulo20223/workspaces-rs", branch = "feature/m1-native-support" }

**Comment by ChaoticTempest** [comment]
`workspaces-rs` version `0.4.0` now officially supports M1!
