### ISSUE TITLE
Update nearcore crate dependencies to 0.13

### ISSUE THREAD

**Issue by austinabell** [near/workspaces-rs#164]
Currently on 0.12 which has some vulnerabilities. Probably unused but also better to have up to date code

**Comment by ChaoticTempest** [comment]
Definitely will need to up these dependencies eventually, but this is currently blocked on `near-jsonrpc-client` requiring `0.12` so will have to wait until it's upped to `0.4.0`. cc @miraclx

**Comment by miraclx** [comment]
Hey @ChaoticTempest, jsonrpc-client version `0.4.0-beta.0` uses nearcore `0.14.0`.

**Comment by ChaoticTempest** [comment]
@miraclx would you recommend using that since it's still in beta or should we wait until it's out completely? It might end up being used as part of a new release for workspaces, so not sure if it's ready for that

**Comment by miraclx** [comment]
Yeah, this release is pretty much stable. I was reserving `0.4.0` for when primitives has been conclusively decoupled from the rest of nearcore but since that's taking a back bench for the meantime, it's going to be a while in beta.

You can go ahead to use this release.

**Comment by ChaoticTempest** [comment]
resolved with https://github.com/near/workspaces-rs/pull/169
