### ISSUE TITLE
How to get sandbox rpc port

### ISSUE THREAD

**Issue by fomotoshi** [near/workspaces-rs#165]
You made the API of workspaces-rs too private. As a result, I can't even get the gas price from the block because your API doesn't provide access to this information, and also, you make your abstraction under RPC too private. I would cope with poor functionality alone, but I can't get info about the RPC port.

Please make your API more open and extendable by 3rd party developers.

**Comment by ChaoticTempest** [comment]
Gas price is from a different query than block, which is currently being worked on to determine the best API to expose. In the meantime, you can get this info via the `near-jsonrpc-client` but definitely not ideal to do it this way
