### ISSUE TITLE
Consider using IntoFuture

### ISSUE THREAD

**Issue by matklad** [near/workspaces-rs#166]
https://doc.rust-lang.org/stable/std/future/trait.IntoFuture.html stabilises soon. It looks like it can be handy for async builders, and something workspaces should use once it hits stable.

https://github.com/Azure/azure-sdk-for-rust/pull/687 is a good example of usage. Might also be a good idea to look at how those crates setup in general, I bet there's a bunch of lessons for workspaces there!

**Comment by ChaoticTempest** [comment]
Ooh, that could be pretty useful since I was thinking of adding a good amount of async builders soon
