### ISSUE TITLE
Call signature

### ISSUE THREAD

**Issue by willemneal** [near/workspaces-rs#2]
This should be a generic that implements Display so that types like serde_json objects can be passed in.

https://github.com/near/sandbox-api/blob/main/src/lib.rs#L74

**Comment by austinabell** [comment]
You're pointing at main so not sure what specifically you are referring to, but it's currently pointing at the method name, and I'm confused why this would be wanted. Perhaps you were pointing at args, but even in that case `Display` would be a weird trait to have it generic on?

**Comment by willemneal** [comment]
I meant args and what I really is needed is that it should be any type that is serializable.

**Comment by austinabell** [comment]
> I meant args and what I really is needed is that it should be any type that is serializable.

The only issue is that with this, it fails to account for serialization that doesn't go through serde. Perhaps we should have `call_raw` which just takes bytes and wrapper functions for serde and borsh for convenience?

**Comment by willemneal** [comment]
That probably sounds like the best plan, though it would be great for one `call` to work for both json and borsh.

**Comment by ChaoticTempest** [comment]
this ones out of date, and we have some convenience functions such as `.json` and `.borsh` now to deserialize output
