### ISSUE TITLE
Cannot compile on Mac M1 and Ubuntu versions after 0.3.1 

### ISSUE THREAD

**Issue by marioiordanov** [near/workspaces-rs#207]
Receiving an error: 
no function or associated item named `from_bytes` found for struct `ed25519_dalek::Signature` in the current scope
   --> /Users/mario/.cargo/registry/src/github.com-1ecc6299db9ec823/near-crypto-0.14.0/src/signature.rs:709:43
    |
709 |                 ed25519_dalek::Signature::from_bytes(signature_data).map_err(|err| {
    |                                           ^^^^^^^^^^ function or associated item not found in `ed25519_dalek::Signature`
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
1   | use ed25519_dalek::ed25519::signature::Signature;
    |
help: there is an associated function with a similar name
    |
709 |                 ed25519_dalek::Signature::to_bytes(signature_data).map_err(|err| {
    |                                           ~~~~~~~~

error[E0599]: no function or associated item named `from_bytes` found for struct `ed25519_dalek::Signature` in the current scope
   --> /Users/mario/.cargo/registry/src/github.com-1ecc6299db9ec823/near-crypto-0.14.0/src/signature.rs:800:47
    |
800 |                     ed25519_dalek::Signature::from_bytes(&array)
    |                                               ^^^^^^^^^^ function or associated item not found in `ed25519_dalek::Signature`
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
1   | use ed25519_dalek::ed25519::signature::Signature;
    |
help: there is an associated function with a similar name
    |
800 |                     ed25519_dalek::Signature::to_bytes(&array)
    |                                               ~~~~~~~~

error[E0599]: no function or associated item named `from_bytes` found for struct `ed25519_dalek::Signature` in the current scope
   --> /Users/mario/.cargo/registry/src/github.com-1ecc6299db9ec823/near-crypto-0.14.0/src/signature.rs:860:47
    |
860 |                     ed25519_dalek::Signature::from_bytes(&array)
    |                                               ^^^^^^^^^^ function or associated item not found in `ed25519_dalek::Signature`
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
1   | use ed25519_dalek::ed25519::signature::Signature;
    |
help: there is an associated function with a similar name
    |
860 |                     ed25519_dalek::Signature::to_bytes(&array)
    |                                               ~~~~~~~~

error[E0599]: no function or associated item named `from_bytes` found for struct `ed25519_dalek::Signature` in the current scope
  --> /Users/mario/.cargo/registry/src/github.com-1ecc6299db9ec823/near-crypto-0.14.0/src/test_utils.rs:59:62
   |
59 |                 Signature::ED25519(ed25519_dalek::Signature::from_bytes(&SIG).unwrap())
   |                                                              ^^^^^^^^^^ function or associated item not found in `ed25519_dalek::Signature`
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
1  | use ed25519_dalek::ed25519::signature::Signature;
   |
help: there is an associated function with a similar name
   |
59 |                 Signature::ED25519(ed25519_dalek::Signature::to_bytes(&SIG).unwrap())
   |

**Comment by ChaoticTempest** [comment]
cargo's dependency resolution here is quite janky for some reason when upgrading from prior versions of workspaces. Recommended you do something like:
```
rm -r ~/.cargo/registry/{cache, src}
```
followed by `cargo clean` in your project repo. After you rebuild, it should be resolved

**Comment by marioiordanov** [comment]
Unfortunately, it didn't work out

**Comment by ChaoticTempest** [comment]
hmm, can you also try deleting your `Cargo.lock` as well?

**Comment by ChaoticTempest** [comment]
Closing this issue for now. Feel free to reopen if this is still an issue
