### ISSUE TITLE
Update to NEAR crates version 0.15

### ISSUE THREAD

**Issue by joshuajbouw** [near/workspaces-rs#209]
The library should always be up to date with latest NEAR crates, and some pre-reqs are required in order for this to happen.

The only library that I had found that also needs updating is the `near-jsonrpc-client-rs` library. I've created a PR for it [here](https://github.com/near/near-jsonrpc-client-rs/pull/110) and will implore the authors of that library to push a new release to be used here.

**Comment by ChaoticTempest** [comment]
resolved with https://github.com/near/workspaces-rs/pull/210
