### ISSUE TITLE
Add `transact_async` for asynchronous transactions

### ISSUE THREAD

**Issue by ChaoticTempest** [near/workspaces-rs#216]
Currently, the flow for sending a transaction is by calling into `transact()`, which is a synchronous operation and blocks the next transaction from happening. This isn't ideal for users who want to have transactions that don't depend on the previous transaction.  So to alleviate this, additional APIs need to be expose so that users can broadcast an asynchronous transaction, while being able to track the status of it.

**Comment by austinabell** [comment]
This could be closed now. I'm just commenting to question the naming. Something more intuitive to me would be a name like `broadcast` rather than `transact_async`. This naming seems like it's referring to the tx type at a Rust level. Wdyt?

**Comment by ChaoticTempest** [comment]
So, underneath in the raw RPC call, it's actually called `broadcast_tx_commit` and `broadcast_tx_async` for `transact` and `transact_async` respectively. People might confuse `broadcast` with both those rpc calls and which one we're referring to. So, I don't think that's the better name here. I feel like `transact_async` conveys that we're trying to perform a transaction while having it be asynchronous, but I can see how it would get confused to be a certain Rust type instead. Not sure how to remedy that part but feels like that isn't too much of a concern from what I see. Or what is the expectation when you go and use `transact_async`?

> This could be closed now.

😅 I would've thought github closed this. It seems to sometimes do it and sometimes don't. Thanks for pointing that this is still open
