### ISSUE TITLE
Sandbox shouldn't require setting a very high ulimit to run

### ISSUE THREAD

**Issue by austinabell** [near/workspaces-rs#237]
Currently, there are the errors that require setting ulimit to run the node for tests:

```
Caused by:
    Hard limit for the number of open files (NOFILE) is too low (10240).  At least 11000 is required.  Set ‘ulimit -Hn’ accordingly and restart the node.', neard/src/cli.rs:423:22
```

This is an unreasonable expectation for users of workspaces and will be a frictional point. We should not have this same requirement for running a sandbox node for testing.

**Comment by ChaoticTempest** [comment]
https://github.com/near/workspaces-rs/pull/241 has the potential fix based purely on how nearcore asserts that error. Haven't tested it below the bounds since I'm not sure how to configure it on macos, but let me know if you're able to test it
