### ISSUE TITLE
Dependency issue with Sandbox

### ISSUE THREAD

**Issue by TrevorJTClarke** [near/workspaces-rs#24]
Im getting the error:
```
error: failed to get `near-sandbox-utils` as a dependency of package `workspaces v0.1.0 (/home/near/workspaces-rs/workspaces)`

Caused by:
  failed to load source for dependency `near-sandbox-utils`

Caused by:
  Unable to update https://github.com/near/sandbox

Caused by:
  failed to find branch `master`

Caused by:
  cannot locate remote-tracking branch 'origin/master'; class=Reference (4); code=NotFound (-3)
```

This seems to be caused by a dependency on the older project "sandbox". 

Can this dep get removed soon?

### Reproduce
Starting from a clean git clone:
```
cargo run --package examples --example nft
```

**Comment by ChaoticTempest** [comment]
@TrevorJTClarke that's weird, https://github.com/near/sandbox is a valid dependency in this repo. I'm running `workspaces-rs` right now on my ubuntu 20.04 machine, clean cloned repo and its working for me.

> Caused by:
>      failed to find branch `master`

This seems to be the cause. Did you update `near-sandbox-utils` to take in `master`? It should be main, or you can force it with:
```
near-sandbox-utils = { git = "https://github.com/near/sandbox", branch="main" }
```

**Comment by TrevorJTClarke** [comment]
@ChaoticTempest looks like the issue was `rust-toolchain`, i set it to nightly just for fun and everything worked as expected.

**Comment by ChaoticTempest** [comment]
hmm, this should be working on stable too as well as nightly. There's no nightly features that this project is making use of. Or  are you saying that switching from nightly to stable fixed the issue? Then that'd make more sense

**Comment by TrevorJTClarke** [comment]
@ChaoticTempest switching from `1.51.0` to nightly fixed running this repo.
However if I change from `nightly` to `stable` now I get this issue:
```workspaces-rs:% cargo run --example status_message                                                                                                                                                      <main ✗>
error: failed to download `impl-codec v0.5.1`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/.cargo/registry/src/github.com-1ecc6299db9ec823/impl-codec-0.5.1/Cargo.toml`

Caused by:
  feature `resolver` is required

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can add
  `cargo-features = ["resolver"]` to enable this feature
  ```
  
  I've also been trying to utilize workspaces-rs in my own repo, however there is definitely some breaking issues that rust nightly seems to just fix (mainly the issue with main/master branches).
  I am still trying to solve the dependencies issues on my repo, as it seems the deps chain in workspaces-rs needs some very specific things or has very strange errors:
  ```bash
   Compiling socket2 v0.4.2
   Compiling is_executable v0.1.2
   Compiling hex v0.3.2
error[E0599]: no method named `is_executable` found for reference `&Path` in the current scope
  --> /home/tc/.cargo/registry/src/github.com-1ecc6299db9ec823/is_executable-0.1.2/src/lib.rs:68:19
   |
68 |     path.as_ref().is_executable()
   |                   ^^^^^^^^^^^^^ method not found in `&Path`
   |
   = help: items from traits can only be used if the trait is implemented and in scope
note: `IsExecutable` defines an item `is_executable`, perhaps you need to implement it
  --> /home/.cargo/registry/src/github.com-1ecc6299db9ec823/is_executable-0.1.2/src/lib.rs:74:1
  ```
  
  Are there any examples of other repos using workspaces-rs yet?

**Comment by ChaoticTempest** [comment]
> error[E0599]: no method named `is_executable` found for reference `&Path` in the current scope

This looks like a compiler issue: try upgrading your rust compiler to the latest or v1.56 at least. That's why nightly seems to fix it because it has already has these features/APIs stabilized

> Are there any examples of other repos using workspaces-rs yet?

not yet  or none that I know of

**Comment by ChaoticTempest** [comment]
@TrevorJTClarke actually I'm seeing these errors while targetting wasm. If that's the case for you, it's best if you split compiling your contract code and the `workspaces` code like so:

In `Cargo.toml` add `workspaces` to `dev-dependencies` instead
```toml
[dev-dependencies]
workspaces = { git = "https://github.com/near/workspaces-rs", rev = "..." }
```
and these configs to your tests:
```rust
#[cfg(not(target_arch = "wasm32"))]
#[cfg(test)]
mod tests {
     fn test() { ... }
}
```

**Comment by TrevorJTClarke** [comment]
Going to mark this as resolved, for future reference the above did work with a little more tiny tweaks.
