### ISSUE TITLE
Sandbox - No such file or directory

### ISSUE THREAD

**Issue by mrLSD** [near/workspaces-rs#255]
When running Github CI have got a lot of errors:

> No such file or directory

Also related to: #193, #252

It's related to the sandbox file not exist.

Proof: https://github.com/aurora-is-near/aurora-eth-connector/actions/runs/3661845365/jobs/6190451337

It is the same as: #193
(I know it was fixed. But for some reason with v0.6 release the issue appeared again)

**Comment by mrLSD** [comment]
It is related to that PR: https://github.com/aurora-is-near/aurora-eth-connector/pull/2

**Comment by mrLSD** [comment]
@ChaoticTempest any news? Seems it's sanbox issue. Where I can open issue for NEAR Sandbox, to force solve that issue?

**Comment by ChaoticTempest** [comment]
@mrLSD I'm still trying to narrow down what is the cause, so hold off from making any issues for now. Would I need permission to run tests if I push a PR into `aurora-eth-connector` to debug this issue? If I do, may I get access?

**Comment by mrLSD** [comment]
@ChaoticTempest invite sended

**Comment by ChaoticTempest** [comment]
thanks!

**Comment by ChaoticTempest** [comment]
No such file or directory error should be fixed with recent [port collision fix](https://github.com/near/workspaces-rs/pull/257)
