### ISSUE TITLE
Switch prints to actual logging solution

### ISSUE THREAD

**Issue by austinabell** [near/workspaces-rs#26]
Currently there are some `println` and `eprintln` calls, but we probably want these to be an actual logging solution so that devs can show/hide/filter or configure their logs.

The most general use case would be using the `log` crate I think, but if we are specifically tying our impl with `tokio`, we might want to use their `tracing` crate

**Comment by matklad** [comment]
>but if we are specifically tying our impl with tokio, we might want to use their tracing crate

`tracing` is from the tokio ecosystem, but it is carefully engineered to not depend on tokio in any way: https://crates.io/crates/tracing/0.1.29/dependencies. So, it should be ok to depend on `tracing` even if `tokio` is not used.

**Comment by austinabell** [comment]
> > but if we are specifically tying our impl with tokio, we might want to use their tracing crate
> 
> `tracing` is from the tokio ecosystem, but it is carefully engineered to not depend on tokio in any way: [crates.io/crates/tracing/0.1.29/dependencies](https://crates.io/crates/tracing/0.1.29/dependencies). So, it should be ok to depend on `tracing` even if `tokio` is not used.

Thanks for the correction, I'm not sure why I had the assumption there was this direct connection, you are correct.
