### ISSUE TITLE
`workspaces::types::PublicKey` doesn’t implement `std::hash::Hash`

### ISSUE THREAD

**Issue by mooori** [near/workspaces-rs#263]
This prevents storing it in a `std::collections::HashSet`, which can be helpful during testing.

`workspaces::types::PublicKey` is a [wrapper](https://docs.rs/workspaces/latest/src/workspaces/types/mod.rs.html#76) around `near_crypto::PublicKey`, which [implements](https://docs.rs/near-crypto/0.15.0/near_crypto/enum.PublicKey.html#impl-Hash-for-PublicKey) `Hash`. So it should be possible for `workspaces::types::PublicKey` to derive `Hash`. Would a PR that adds `Hash`to the derived traits be welcome?

**Comment by ChaoticTempest** [comment]
Oh thanks for bringing this up. Lots of types in workspaces are there more on a need basis, so some stuff might've been missed. There's a couple things missing from `PublicKey` that would be nice to have as well. I'll include this in that PR as well
