### ISSUE TITLE
Prevent running server on exposed network address

### ISSUE THREAD

**Issue by agostbiro** [near/workspaces-rs#276]
When I run the workspace as part of an integration test I get this popup on the latest MacOS:

![Screenshot 2023-06-21 at 11 39 45](https://github.com/near/workspaces-rs/assets/5764438/a32cbf29-f69f-4102-b8d1-e8195572c526)

This indicates that the server tries to listen on an exposed network address. Ideally, the server would only run on localhost by default and then this popup wouldn't show.

A quick look at the [source](https://github.com/near/workspaces-rs/blob/26ca5aee8477fcf59fdb25bfa4a612989864e4da/workspaces/src/network/server.rs#LL18C36-L18C36) shows that the default address is indeed localhost:

```rust
pub const DEFAULT_RPC_URL: &str = "http://localhost";
```

so there must be something weird going on to get this popup. 

Happy to dig in and provide a PR if you think it's important.

**Comment by frol** [comment]
@agostbiro Good catch. Yeah, it is indeed annoying and it is better to solve it. I believe it is not RPC that is not running on localhost, but the P2P part of neard. Workspaces-rs sandbox launches neard server and neard uses two TCP ports: (1) [RPC](https://github.com/near/nearcore/blob/140c573a8fee995f0590fda52a965a91fe31bcbf/nearcore/src/config.rs#L287), (2) [p2p network](https://github.com/near/nearcore/blob/140c573a8fee995f0590fda52a965a91fe31bcbf/nearcore/src/config.rs#L292). Workspaces-rs patches the config to specify the proper RPC IP:address:

https://github.com/near/workspaces-rs/blob/c31a955df8a55a6c82cedaaf820ed9236ee1fee5/workspaces/src/network/server.rs#L100

My guess is that it does not patch the `network` addr (I see that it seems to patch the port)

Please, address it.

**Comment by agostbiro** [comment]
Thanks @frol , that was helpful! It turns out that there were two separate causes for the popups, so it was a bit involved to track them down, but the fix is in now: https://github.com/near/workspaces-rs/pull/277

**Comment by frol** [comment]
Resolved in #277
