### ISSUE TITLE
How to call a method on the `contract` and sign it by the `user`?

### ISSUE THREAD

**Issue by khorolets** [near/workspaces-rs#32]
Hey there! I'm trying to start using this project and I really love it, but I guess I have use-cases not covered yet.

Basically, I have a `contract` deployed and I need to check the `user` (different from the owner) can use it properly. 

I've managed to find `worker.dev_create()` function and get the user but I'm stuck with trying to call the `contract` and not sign it by the owner.

```rust
pub async fn call(
        &self,
        contract: &Contract,
        method: String,
        args: Vec<u8>,
        deposit: Option<Balance>,
    ) -> anyhow::Result<CallExecutionDetails> {
        self.client()
            .call(
                contract.signer(),
                contract.id().clone(),
                method,
                args,
                None,
                deposit,
            )
            .await
            .map(Into::into)
    }
```

the function `call` takes only `contract` arg and makes it a callee and a caller which is not always the desired behavior. Was it done intentionally or it should be changed? 

I guess I can open a PR if you agree that this should be changed. 

Assign me on this issue if you want me to open a PR. Thanks!

**Comment by ChaoticTempest** [comment]
@khorolets sounds great. Yeah, this was definitely a case that wasn't accounted for. I'd be happy if you created a PR for it. There's also an alternative with call builder being worked on too: https://github.com/near/workspaces-rs/tree/feat/call-builder

Where you can do:

```rust
let worker = workspaces::sandbox();
let root = worker.root_account();

root.call(&worker, contract_id, "function")
   .with_args( ... )
   .with_gas( /*optional: defaults to an internal constant */ )
   .with_deposit( /* optional: defaults to 0 */)
   .transact()
   .await?;

```

**Comment by khorolets** [comment]
@ChaoticTempest have you considered opening a draft PR for that? I can't understand which approach to stick to :)

**Comment by ChaoticTempest** [comment]
@khorolets there you go: https://github.com/near/workspaces-rs/pull/33
