### ISSUE TITLE
Do not require `&worker` when executing `{contract, account}.call`

### ISSUE THREAD

**Issue by ChaoticTempest** [near/workspaces-rs#37]
`Account`s and `Contract`s do not need to take in worker when performing calls, but would end up requiring type parameters in the current state of the API. Once `Worker` no longer takes a type parameter and is resolved with this issue [https://github.com/near/workspaces-rs/issues/31](https://github.com/near/workspaces-rs/issues/31), then we can just add a `Worker` pretty simply into these types.

**Comment by austinabell** [comment]
> `Account`s and `Contract`s do not need to take in worker when performing calls, but would end up requiring type parameters in the current state of the API. Once `Worker` no longer takes a type parameter and is resolved with this issue #31, then we can just add a `Worker` pretty simply into these types.

Well, regardless of choosing traits vs. no traits this can still be done, but would just be a breaking change to add the generic on accounts and contracts.

**Comment by ChaoticTempest** [comment]
closed with https://github.com/near/workspaces-rs/pull/181
