### ISSUE TITLE
Errors can cause long block times for retries

### ISSUE THREAD

**Issue by TrevorJTClarke** [near/workspaces-rs#41]
I came across a situation where making a `.call` that has bad args or bad response (`.json()?` fails for whatever reason), that causes the retries (HERE:     `let retry_strategy = ExponentialBackoff::from_millis(10).map(jitter).take(5);`) to delay the resolution of a call. anyhow makes certain error situations go unnoticed making the developer (me) confused until much more debugging.

I suggest 2 ideas:
1. make retries configurable, default to 5?
2. potentially have a universal error catch that reports upon flag if found within `.call` or `.view` so developer is alerted to the possibility that it is their code, not the network/sandbox.

**Comment by itegulov** [comment]
I think we could add some logging to retry logic and to rpc responses. While this would not fix the root of the issue, it would improve the visibility on what is going on under the workspaces hood and ease the debugging process. So that might be a good short-term solution for the problem while we figure out a proper retry mechanism.

**Comment by itegulov** [comment]
@ChaoticTempest would you agree that we just need to pick a more lenient backoff algorithm by default? I suggest either using Fibonacci backoff or reducing exponential base to like a 5 (i.e. 3 seconds delay on the 5th retry). As is we are waiting 100 seconds for the final retry which does not make a lot of sense to me.

**Comment by itegulov** [comment]
Configuring retries might be valuable too, but I don't want to unnecessarily bloat the API as we are still in the early stages of workspaces' life.

**Comment by ChaoticTempest** [comment]
> Configuring retries might be valuable too, but I don't want to unnecessarily bloat the API as we are still in the early stages of workspaces' life.

yeah I agree, let's have configuration management down the line, but right now trying to rush that part will be a pain to manage later since configuration management isn't exactly the easiest thing to add
