### ISSUE TITLE
Better support for Error assertion

### ISSUE THREAD

**Issue by TrevorJTClarke** [near/workspaces-rs#43]
Sorry if this is a n00b issue. :|

Here is a basic example of what i'd like to do:
```rust
// try to unregister agent again, check it fails
    let fail_agent = agent
        .call(&worker, contract.id().clone(), "register_agent")
        .args_json(json!({}))?
        .deposit(parse_near!("0.00226 N"))
        .transact()
        .await
        .context("Failed to re-register")?;
    println!("agent fail_agent {:#?}", fail_agent);
   // i know - this is bad, but you get the idea
   assert!(fail_agent.is_error());
```

however it seems there are no exported ways that I can check the failure? Here is the response i get:
```
agent fail CallExecutionDetails {
    status: Failure(ActionError(ActionError { index: Some(0), kind: FunctionCallError(ExecutionError("Smart contract panicked: Agent already exists: Agent { status: Active, payable_account_id: AccountId(\"agent_1.dev-20211221202721-35660262466987\"), balance: U128(2260000000000000000000), total_tasks_executed: U128(0), last_missed_slot: 0 }. Refunding the deposit.")) })),
    total_gas_burnt: 6197905373141,
}
```

Which is exactly the response i would expect, and am testing to make sure it fails. Is there an example or easy way to peel back the error onion?
Heres the only spot i could find where it highlights another way that gets strange: https://github.com/near/workspaces-rs/blob/main/examples/src/spooning.rs#L116-L129

**Comment by ChaoticTempest** [comment]
The following should yield us a `CallExecutionDetails` object
```rust 
 let outcome = agent
        .call(&worker, contract.id().clone(), "register_agent")
        .args_json(json!({}))?
        .deposit(parse_near!("0.00226 N"))
        .transact()
        .await?;
```

To check for the failure of the call, we can look at the `status` field in `CallExecutionDetails`. It's a `near_primitives::views::FinalExecutionStatus`, and we want the `Failure` case where we can match it against a specific `near_primitives::errors::TxExecutionError` error.
```rust
match outcome.status {
    FinalExecutionStatus::Failure(e) => println!("{:?}", e),
    _ => ...,
}
```
Forewarning though, this is likely to change in the future since the error types could be moved out of `near_primitives` into a separate crate

**Comment by TrevorJTClarke** [comment]
This was exactly what i was missing. Closing.
