### ISSUE TITLE
Allow empty args for call/view

### ISSUE THREAD

**Issue by austinabell** [near/workspaces-rs#48]
Currently expects at least empty JSON. This is defaulted within the `CallBuilder` to be this, but it should be absolutely valid to be empty bytes or some other protocol to JSON. This might involve making a change to the RPC client, just opening issue here for tracking

**Comment by ChaoticTempest** [comment]
Related issue: https://github.com/near/workspaces-rs/issues/36

**Comment by austinabell** [comment]
ah oops I didn't assume they were the same from the title, let's just close this in favour of that
