### ISSUE TITLE
How do you less verbose output

### ISSUE THREAD

**Issue by willemneal** [near/workspaces-rs#61]
Currently when running tests I get 

```
Jan 25 15:44:51.390  INFO neard: Version: trunk, Build: 2c9375e, Latest Protocol: 48
Jan 25 15:44:51.395  INFO near: Generated node key, validator key, genesis file in /var/folders/vp/8bpjzhtd71s6vyy6382ylq440000gn/T/sandbox-22709
Started sandbox: pid=3954
Jan 25 15:44:51.405  INFO neard: Version: trunk, Build: 2c9375e, Latest Protocol: 48
Jan 25 15:44:51.411  INFO near: Did not find "/var/folders/vp/8bpjzhtd71s6vyy6382ylq440000gn/T/sandbox-22709/data" path, will be creating new store database
Jan 25 15:44:51.929  INFO stats: Server listening at ed25519:4Fe2CUwyk1udJhVYELR2XcK3rQLKQWToCTqGDUmyVmgy@0.0.0.0:15148
Jan 25 15:45:01.935  INFO stats: #      16 CtKDYPhFxX79m25tUY5cgM1fVdYXaFCfezdEA934hRvB V/1  0/0/40 peers ⬇ 0 B/s ⬆ 0 B/s 1.60 bps 827.30 Ggas/s CPU: 0%, Mem: 54.2 MiB 
```

Is there a way to silence this?

**Comment by itegulov** [comment]
See this: https://github.com/near/workspaces-rs/issues/53. Unfortunately, hiding these logs is not that straightforward as they come from a pre-compiled sandbox binary that does not respect the logging configuration (`RUST_LOG`, `RUST_LOG_STYLE` and others). That being said, we could most likely just divert the sandbox stdout to `/dev/null` or something by default as a temporary solution.

**Comment by ChaoticTempest** [comment]
So was just testing this out, but `RUST_LOG` still works, it's just that we need to pass this env-var down to the binary being run underneath. Just need to add this into `near-sandbox-utils` and we should be good to go. Only downside is that we'll probably need to add a `.cargo/config.toml` if people want to see the logs again

**Comment by ChaoticTempest** [comment]
Here's the change with `near-sandbox-utils`: https://github.com/near/sandbox/pull/23. Will update workspaces after that's merged
