### ISSUE TITLE
Why does dev-deploy on sandbox make a throw away account?

### ISSUE THREAD

**Issue by willemneal** [near/workspaces-rs#62]
This makes sense on testnet, but locally it just seems to generate extra files.

**Comment by itegulov** [comment]
Hmm, what would the alternative be though?

> locally it just seems to generate extra files.

That is true, but I think the intended way to use workspaces is to just add `.near-credentials` to .gitignore and forget that the folder exists. Not sure what is the problem with those extra files other than taking a few MBs of space on your PC.

**Comment by austinabell** [comment]
Well, I think at least an improvement to this is to clean up the credentials after they are used, or just never persist them to a file if only used for the test execution.

**Comment by ChaoticTempest** [comment]
outdated. Current version does nothing about credentials and requires users to specify `account.store_credentials`
