### ISSUE TITLE
Decide on and switch error handling to something more generally usable

### ISSUE THREAD

**Issue by austinabell** [near/workspaces-rs#7]
Currently just using string errors for everything, but would probably be best for long-term maintainability if we pick an error type/pattern to use before the API surface gets large and starts to be used.

Options:
- Concrete types that implement `std::error::Error`
  - Probably too tedious to have many error types for this kind of API
  - Can use https://github.com/dtolnay/thiserror to derive for convenience on impls
- `Box<dyn std::error::Error>` error types
  - Reduces code internally to avoid having to convert errors from other crates, but can be annoying to use in cases
- Anyhow Error https://github.com/dtolnay/anyhow
  - probably just a better version of the above, doesn't seem like it adds any overhead to a user other than potentially being a bit confusing to use for new Rust devs, but probably not much more than `String` errors
- Keep `String` error on public APIs, use one of the above internally for convenience

I personally think using something like anyhow makes sense for this kind of API that is just used for testing, but let me know if you guys have thoughts. Concrete error types could also be an option but this might become tedious without any real benefit

**Comment by ChaoticTempest** [comment]
`anyhow` seems to be a good match for this so far. Very thin and can easily swap between errors that implement `std::error::Error`. Anyhow also offers downcasting to a more specific error, so a lot better than purely just handling a `String` and trying to grab its contents. Let's just swap over `anyhow` then. It's also already being used somewhat internally

**Comment by austinabell** [comment]
> `anyhow` seems to be a good match for this so far. Very thin and can easily swap between errors that implement `std::error::Error`. Anyhow also offers downcasting to a more specific error, so a lot better than purely just handling a `String` and trying to grab its contents. Let's just swap over `anyhow` then. It's also already being used somewhat internally

using boxed std errors [can also be downcasted](https://doc.rust-lang.org/std/error/trait.Error.html#method.downcast) but yeah in my anecdotal experience using these boxed errors is not ideal and anyhow is just a cleaner alternative in almost every way.

**Comment by austinabell** [comment]
@ChaoticTempest we can close this now, or do you think this is still unfinished?

**Comment by ChaoticTempest** [comment]
Definitely can close this now. Thanks for the reminder
