### ISSUE TITLE
docs.rs build failing with current version

### ISSUE THREAD

**Issue by austinabell** [near/workspaces-rs#86]
https://docs.rs/crate/workspaces/0.1.1/builds/496003

This broke with 0.1.1 release, and we should fix this before it gets to 0.2

Failing because it tries to download sandbox binary by default

**Comment by austinabell** [comment]
https://docs.rs/crate/workspaces/0.2.0/builds/537593 failed again for 0.2

**Comment by ChaoticTempest** [comment]
yeah it looks like docs rs actually has their own specific build that I noticed. It requires us to reference an environment variable. Not too bad of a fix, but this time, let's get a local build running to just make sure. We can make a patch release later since this doesn't affect anything API-wise

**Comment by austinabell** [comment]
Having a working docs.rs page is very important for people using this. We should prioritize this

Also might be a good time to scan the docs to make sure key things are documented

**Comment by ChaoticTempest** [comment]
Definitely. I'll try getting something up tomorrow. The docs should be mostly covered. All things exposed should have docs covered at least

**Comment by itegulov** [comment]
Closed by https://github.com/near/workspaces-rs/pull/115
