### ISSUE TITLE
Add helper functions

### ISSUE THREAD

**Issue by mikedotexe** [near/workspaces-rs#9]
Here is a shortlist of helpful functionality that have been with simulation tests that are worth having for sandbox testing:

- [ ] did tx succeed?
- [ ] what's the error
- [ ] what's the log
- [ ] logs_contain value (suggestion)
- [ ] unwrap json ability
- [ ] unwrap borsh ability

**Comment by ChaoticTempest** [comment]
Outdated issue, all things here have since been implemented and can be found in `CallExecutionDetails` convenience functions
